---

- name: Create and start services
  ansible.builtin.block:
    - name: Get list of services
      shell: "{{ docker_compose }} -p {{ container_name_prefix }} config --services"
      args:
        chdir: "{{ sources_root }}/albs-web-server"
      register: services

    - name: Create and start each service individually
      shell: "{{ docker_compose }} -p {{ container_name_prefix }} up -d --build --force-recreate {{ item }}"
      args:
        chdir: "{{ sources_root }}/albs-web-server"
      when: item not in excluded_containers
      loop: "{{ services.stdout_lines }}"
  when:
    - excluded_containers

- name: Create and start services
  ansible.builtin.shell: "{{ docker_compose }} -p {{ container_name_prefix }} --compatibility up -d --build --force-recreate"
  args:
    chdir: "{{ sources_root }}/albs-web-server"
  register: output
  when:
    - not excluded_containers or excluded_containers == ""
